from typing import Any, Optional, Tuple


class Injector:
    def __init__(self) -> None: ...
    def attach(self, pid: int) -> None: ...
    def inject(self, path: bytes) -> int: ...
    def uninject(self, handle: int) -> None: ...
    def detach(self) -> None: ...


class InjectorException(Exception):
    args: Tuple[str, int, Optional[str]]
